---
title: "Defaunation effects on the evolution of plant species"
author: "Carine Emer"
date: "04/09/2019"
output: html_document
---
Projeto Parcelas/Biota
ED of plants in open and closed plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(picante)
library(phytools)
library(ape)
library(caper)
library(plyr)
library(reshape)
library(reshape2)
library(data.table)
library(dplyr)
library(bipartite)
library(Matrix)
library(lme4)
library(tibble)
library(phangorn)
library(plotly)
library(taxize)
```

```{r input data}
setwd("~/Dropbox/BIOTA/Evol_distinct/ED_biota")
#load("~/Dropbox/BIOTA/Evol_distinct/ED_biota/ms_biota.RData")

CAR_com<-read.table("CARcomm.txt", row.names=1, h=T)
ITA_com<-read.table("ITAcomm.txt", row.names=1, h=T)
CBO_com<-read.table("CBOcomm.txt", row.names=1, h=T)
VG_com<-read.table("VGcomm.txt", row.names=1, h=T)

#communities<-read.csv("data_communities nat.csv")
car_rpool<-read.csv("cardoso_regional_pool.csv", h=T)
ita_rpool<-read.csv("ita_regional_pool.csv", h=T)
cbo_rpool<-read.csv("cbo_regional_pool.csv", h=T)
vg_rpool<-read.csv("ita_regional_pool.csv", h = T)

```

```{r taxonomy}
#getkey(x="b93f5fa9-63ed-44df-a903-f486f8038f22", service="tropicos")


valesca<- read.csv("Life_Form_valesca.csv", h = T)

taxonomy<-join(vg_rpool, valesca, by = "species", type = "left")
taxonomy1<-subset(taxonomy,!duplicated(taxonomy[,1])) # using unique spp for the traits correlations
head(taxonomy2)
taxonomy2<-subset(taxonomy1, select=c("species","genus","family"))

write.csv(taxonomy2, "vg_plants_taxonomy.csv")

#car_rpool_tax$species<-gsub(' ', '_', car_rpool_tax$species)
#cbo_rpool_tax$species<-gsub(' ', '_', cbo_rpool_tax$species)
```


```{r building tree plants, include= =FALSE}

########## PLANTS 
# read in the megaphylogeny, obtained when downloading Phylomaker
phylo<-read.tree("PhytoPhylo.tre") 
# read in the nodes information of the megaphylogeny.
nodes<-read.csv("nodes.csv",header=T, sep="\t") 
source("S.PhyloMaker")
#plants_taxon<-read.csv("plants_list_taxonomy_regional_pool.csv")
# add list of species at the regional pool

ita_rpool_tax<-read.csv("ita_plants_taxonomy.csv", h = T)
vg_rpool_tax<-read.csv("vg_plants_taxonomy.csv", h = T)

# run the function S.PhyloMaker
result_plants<-S.PhyloMaker(splist=vg_rpool_tax, tree=phylo, nodes=nodes)

#par(mfrow=c(1,3),mar=c(0,0,1,0)) # show the phylogenies of the three scenarios.
#plot(result_plants$Scenario.1,cex=1.1,main="Scenario One") ## we chose to work with scenario 1 that "assigns"add genera or species as basal polytomies within their families of genera" 
#plot(result$Scenario.2,cex=1.1,main="Scenario Two")
#plot(result$Scenario.3,cex=1.1,main="Scenario Three")
is.binary.tree(result_plants$Scenario.1)

#write.nexus(result_plants$Scenario.1,file="tree_phylomaker_1_ita.nex") ### saving nexus format
#write.tree(result_plants$Scenario.1,file="tree_phylomaker_1_ita.nwk") ### saving newick format

mytree<-result_plants$Scenario.1

########## using the saved newick format of the chosen scenario to plot the tree, or read the correspondent vector created above (mytree)
#tree_plants<-read.tree("tree_phylomaker_1.nwk")
tree_plants<-mytree
#plot(tree_plants, cex=0.5) 
#zoom(tree_plants,240:280,show.node.label=TRUE)
#axisPhylo(tree_nplants)
branching.times(tree_plants)

#library(ape)
source("PolytomyResolver.R") #### function in the PolytomyResolver.R sent by Miguel Verdu

#tree_plants<-read.tree("tree_phylomaker_1.nwk") ### read the tree resolved in PhyloMaker, or use the vector created above

PolytomyResolver(tree_plants,file="tree_plants_vg") ### tree_plants.xml goes to BEAST - takes a few hours

### then, generates tree_plants.trees which should be read again here to run the following:

trees<-read.nexus("tree_plants_vg.trees") ## huge file


######### after BEAST

postburnin<-trees[(0.25*length(trees)):length(trees)] #drops 25% of trees as burning 
 
tt100<-sample(postburnin, size=100) #randomly selects 100 trees
#write.tree(tt100[[1]])
#plot(tt100,show.tip.label=FALSE)
is.binary(tt100[[1]])

tt100_1<-tt100[[1]]
plot(tt100_1, cex = 0.4)
write.tree(tt100,"vg_plants_100trees.nwk")

```

```{r ED plants, include= =FALSE}

#tt100<-read.newick("car_plants_100trees.nwk")
#tt100<-lapply(tt100,drop.tip,tip="Duranta_erecta")


#### evolutionary distinctiveness, function in Picante
ED100_p<-lapply(tt100, evol.distinct)

#### organize the list of EDs in a dataframe - columns
for (i in 1: length(ED100_p)){
ED100_p[[i]]<-ED100_p[[i]][order(ED100_p[[i]]$Species),]}
ED100_p<-do.call(cbind.data.frame,ED100_p)
ED100_p<-ED100_p[,-seq (3, 200, 2),] ## exclude columns with species names but first one
rownames(ED100_p)<-ED100_p[,1] 
ED100_p<-ED100_p[,-1] ## exclude first column
colnames(ED100_p)<-paste("tree",1:100,sep="") ## give name to each column
ED100_p <- cbind(Plant_Species2 = rownames(ED100_p), ED100_p) # give name to first column to later match with other df
rownames(ED100_p) <- NULL

write.csv(ED100_p,"vg_plants_ED100.csv")

ED100_p[,102]

ED100_p["mean_ed"] <- rowMeans(ED100_p[,2:101])
ED100_p["sum_ed"] <- rowSums(ED100_p[,2:101])
ED100_p["sd_ed"] <-apply(ED100_p[,2:101], 1, sd)

## change name of the object
mean_ed_vg<-ED100_p[,-(2:101)]
colnames(mean_ed_vg)[1]<-"species"

# check names
setdiff(tt100_1$tip.label, colnames(VG_com))
setdiff(colnames(VG_com), tt100_1$tip.label)

colnames(VG_com)[which(names(VG_com) == "Dalbergia_frutescens_var._frutescens")] <- "Dalbergia_frutescens"

### combine mean_ed_car$mean_ed in the CAR_com
mtx1<-as.matrix(VG_com)
list1<-matrix2sample(mtx1)
colnames(list1)[3]<-"species"
treat_ed<-join(list1,mean_ed_vg, by= "species", type = "left")

write.csv(treat_ed, "VG_ED.csv")

```

```{r function figure}
#Function for plotting means, s.e., C.I.

#For a figure with points with Standard error bars
#first we need to define function summarySE
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  #library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     measurevar = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column
  #datac <- rename(datac, c("mean" = measurevar))

  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval:
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
```


```{r figure }
### Make figures for the SUm of ED as well, not only Mean
mpd<-read.csv("Overall_MPD.csv", header = T)

####### 
#FIGURE MPDz CAR
###############################

carcf<-read.csv("CAR_ED.csv", header = T)

#cbocf<-subset(all_areas,all_areas$Site=="CBO"& all_areas$mpd.obs.z!="NA")

### combine cbocf with MPD to get RealTime

mpd_car<-subset(mpd, Site == "CAR")
carcf<-join(carcf,mpd_car, by= "plotID", type = "left")
dim(carcf)
carcf <- carcf[,!duplicated(names(carcf))]
head(carcf)
range(carcf$RealTime)

#relevel treatment open as baseline for tests and estimates
carcf$Treatment <- relevel(carcf$Treatment, ref = "open")

#set Time  as factorial
carcf$Time<-as.factor(carcf$Time)

#load packages
#library(ggplot2)
#library(plyr)

#then create summary dataframe
CARMPDzInt <- summarySE(carcf,measurevar="mean_ed",groupvars=c("Treatment","RealTime"))
CARMPDzInt
tiff('CAR_ED.tiff', units="in", width=5, height=4, res=600)
pd <- position_dodge(2) # move them 1 to the left and right
plot_car<-ggplot(CARMPDzInt, aes(x = RealTime, y = measurevar, colour =Treatment,group=Treatment)) +
  geom_errorbar(aes(ymin=measurevar-se, ymax=measurevar+se), colour="black", width=1,position=pd)+
  geom_point(aes(shape=Treatment,colour=Treatment),size=3,position=pd) +
  scale_colour_manual(values=c("blue", "chocolate2")) +
  scale_x_continuous(limits = c(-1,90)) +
  scale_y_continuous(limits = c(55,80)) +
  geom_line(size=1,position=pd) +
  labs(x = "Time (months)")+
  labs(y = "Evolutionary Distinctness (mean)")+
  # theme_bw()
  theme_classic() +
  theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"),
    text=element_text(size=16))
print(plot_car + ggtitle("Ilha do Cardoso"))
dev.off()


#FIGURE MPDz CBO
###############################
cbocf<-read.csv("CBO_ED1.csv", header = T)
mpd<-read.csv("Overall_MPD.csv", header = T)
#cbocf<-subset(all_areas,all_areas$Site=="CBO"& all_areas$mpd.obs.z!="NA")

### combine cbocf with MPD to get RealTime

mpd_cbo<-subset(mpd, Site == "CBO")

cbocf<-join(cbocf,mpd_cbo, by= "plotID", type = "left")
dim(cbocf)
cbocf <- cbocf[,!duplicated(names(cbocf))]
head(cbocf)
range(cbocf$RealTime)

#relevel treatment open as baseline for tests and estimates
cbocf$Treatment <- relevel(cbocf$Treatment, ref = "open")

#set Time  as factorial
cbocf$Time<-as.factor(cbocf$Time)

#load packages
#library(ggplot2)
#library(plyr)

#then create summary dataframe
CBOMPDzInt <- summarySE(cbocf,measurevar="mean_ed",groupvars=c("Treatment","RealTime"))
CBOMPDzInt
tiff('CBOMPDz.tiff', units="in", width=5, height=4, res=600)
pd <- position_dodge(2) # move them 1 to the left and right
plot_cbo<-ggplot(CBOMPDzInt, aes(x = RealTime, y = measurevar, colour =Treatment,group=Treatment)) +
  geom_errorbar(aes(ymin=measurevar-se, ymax=measurevar+se), colour="black", width=1,position=pd)+
  geom_point(aes(shape=Treatment,colour=Treatment),size=3,position=pd) +
  scale_colour_manual(values=c("blue", "chocolate2")) +
  scale_x_continuous(limits = c(-1,90)) +
  scale_y_continuous(limits = c(50,80)) +
  geom_line(size=1,position=pd) +
  labs(x = "Time (months)")+
  labs(y = "Evolutionary Distinctness (mean)") +
  # theme_bw()
  theme_classic() +
  theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"),
    text=element_text(size=16))

print(plot_cbo + ggtitle("Carlos Botelho"))
dev.off()

#FIGURE MPDz ITA
###############################
itacf<-read.csv("ITA_ED.csv", header = T)
#itacf<-subset(all_areas,all_areas$Site=="ITA"& all_areas$mpd.obs.z!="NA")

### combine cbocf with MPD to get RealTime
mpd_ita<-subset(mpd, Site == "ITA")
itacf<-join(itacf,mpd_ita, by= "plotID", type = "left")
dim(itacf)
itacf <- itacf[,!duplicated(names(itacf))]
head(itacf)


#relevel treatment open as baseline for tests and estimates
itacf$Treatment <- relevel(itacf$Treatment, ref = "open")

#set Time  as factorial
itacf$Time<-as.factor(itacf$Time)

#load packages
#library(ggplot2)
#library(plyr)

#then create summary dataframe
ITAMPDzInt <- summarySE(itacf,measurevar="mean_ed",groupvars=c("Treatment","RealTime"))
ITAMPDzInt
tiff('ITAMPDz.tiff', units="in", width=5, height=4, res=600)
pd <- position_dodge(2) # move them 1 to the left and right
plot_ita<-ggplot(ITAMPDzInt, aes(x = RealTime, y = measurevar, colour =Treatment,group=Treatment)) +
  geom_errorbar(aes(ymin=measurevar-se, ymax=measurevar+se), colour="black", width=1,position=pd)+
  geom_point(aes(shape=Treatment,colour=Treatment),size=3,position=pd) +
  scale_colour_manual(values=c("blue", "chocolate2")) +
  scale_x_continuous(limits = c(-1,90)) +
  scale_y_continuous(limits = c(50,90)) +
  geom_line(size=1,position=pd) +
  labs(x = "Time (months)")+
  labs(y = "Evolutionary Distinctness (mean)")+
  # theme_bw()
  theme_classic() +
  theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"),
    text=element_text(size=16))
print(plot_ita + ggtitle("Itamambuca"))
dev.off()



#FIGURE MPDz VG
###############################
vgcf<-read.csv("VG_ED.csv", header = T)
mpd<-read.csv("Overall_MPD.csv", header = T)
#vgcf<-subset(all_areas,all_areas$Site=="vg"& all_areas$mpd.obs.z!="NA")

### combine vgcf with MPD to get RealTime

mpd_vg<-subset(mpd, Site == "VGM")

vgcf<-join(vgcf,mpd_vg, by= "plotID", type = "left")
dim(vgcf)
vgcf <- vgcf[,!duplicated(names(vgcf))]
head(vgcf)
range(vgcf$RealTime)
range(vgcf$sum_ed)

#relevel treatment open as baseline for tests and estimates
vgcf$Treatment <- relevel(vgcf$Treatment, ref = "open")

#set Time  as factorial
vgcf$Time<-as.factor(vgcf$Time)

#load packages
#library(ggplot2)
#library(plyr)

#then create summary dataframe
VGMPDzInt <- summarySE(vgcf,measurevar="mean_ed",groupvars=c("Treatment","RealTime"))
VGMPDzInt
tiff('VGMPDz.tiff', units="in", width=5, height=4, res=600)
pd <- position_dodge(2) # move them 1 to the left and right
plot_vg<-ggplot(VGMPDzInt, aes(x = RealTime, y = measurevar, colour =Treatment,group=Treatment)) +
  geom_errorbar(aes(ymin=measurevar-se, ymax=measurevar+se), colour="black", width=1,position=pd)+
  geom_point(aes(shape=Treatment,colour=Treatment),size=3,position=pd) +
  scale_colour_manual(values=c("blue", "chocolate2")) +
  scale_x_continuous(limits = c(-1,90)) +
  #scale_y_continuous(limits = c(6000, 9000))
  scale_y_continuous(limits = c(60, 90))+
  geom_line(size=1,position=pd) +
  labs(x = "Time (months)")+
  labs(y = "Evolutionary Distinctness (mean)") +
  # theme_bw()
  theme_classic() +
  theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black"),
    text=element_text(size=16))

print(plot_vg + ggtitle("Vargem Grande"))
dev.off()


```




```{r}

save.image("ms_biota.RData")
```


